_53(admins) make messages table component be similar to the users table component
tineret-spearanta-oradea/hopecamp-website pull request #108
Opened 2024-09-24 16:02 UTC by MaxiFrancis

2024-09-25 06:26 UTC, MaxiFrancis commented
https://github.com/user-attachments/assets/05b128fd-e8bd-4200-93e0-e87b92c569ea
On save it shows the rows but just for a bit.

2024-09-26 07:23 UTC, ghefraim commented
![image](https://github.com/user-attachments/assets/31a4f29a-9c33-4591-a503-c2734ee43f15)

2024-09-26 07:28 UTC, ghefraim requested changes
Pls remove the "More" functionality from the Messages table, and pls fix the data not being shown

2024-09-26 07:28 UTC, ghefraim commented on src/components/admins/MessagesTable.jsx
> +        Header: "More",
I think we can remove this "More" column. There are no extra details to be shown here

2024-09-26 07:43 UTC, closed without merging